version: 2.1

jobs:
  post-to-ci:
    steps:
      - run:
          command: |
            curl --location --request POST 'http://fa196db707ec.ngrok.io/pipeline/register' \
              --header 'Content-Type: application/json' \
              --data-raw '{
                "circleci-build-url": "'$CIRCLE_BUILD_URL'"
              }'

workflows:
  test:
    jobs:
      - post-to-ci
